
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'rightNewleftLessLessEqualGreaterGreaterEqualEqualsDifferentrightLPARENTHESISRPARENTHESISADD Alter AlterB Bool Break CALL COMMA Case DIV Different Else Equals Este False Greater GreaterEqual Hammer ID IsTrue LPARENTHESIS Less LessEqual MUL MoveLeft MoveRight New Norte Num Number Oeste PRINCIPAL PrintValues Proc QUOTES RPARENTHESIS Repeat SEMMICOLOM SUB Stop Sur Then True Until Values When WhileProced : Proc ID LPARENTHESIS instrucciones RPARENTHESIS SEMMICOLOM\n              | Proc PRINCIPAL LPARENTHESIS RPARENTHESIS SEMMICOLOMinstrucciones : varDeclaration\n                     | Values_f\n                     | Alter_f Values_f : Values LPARENTHESIS ID COMMA valorDato RPARENTHESIS SEMMICOLOM\n                | LPARENTHESIS ID COMMA Alter_f RPARENTHESIS SEMMICOLOMAlter_f : LPARENTHESIS ID COMMA RPARENTHESISvarDeclaration : New ID LPARENTHESIS tipoDatos COMMA valorDato RPARENTHESIS SEMMICOLOM tipoDatos : Bool\n                 | NumvalorDato : True \n                | False  \n                | Number'
    
_lr_action_items = {'Proc':([0,],[2,]),'$end':([1,19,21,],[0,-2,-1,]),'ID':([2,7,12,18,24,],[3,15,17,23,31,]),'PRINCIPAL':([2,],[4,]),'LPARENTHESIS':([3,4,5,13,17,20,],[5,6,7,18,22,24,]),'New':([5,],[12,]),'Values':([5,],[13,]),'RPARENTHESIS':([6,8,9,10,11,20,25,26,34,35,36,37,38,39,40,43,44,],[14,16,-3,-4,-5,26,32,-8,41,-12,-13,-14,26,-7,42,-6,-9,]),'SEMMICOLOM':([14,16,32,41,42,],[19,21,39,43,44,]),'COMMA':([15,23,27,28,29,31,],[20,30,33,-10,-11,38,]),'Bool':([22,],[28,]),'Num':([22,],[29,]),'True':([30,33,],[35,35,]),'False':([30,33,],[36,36,]),'Number':([30,33,],[37,37,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'Proced':([0,],[1,]),'instrucciones':([5,],[8,]),'varDeclaration':([5,],[9,]),'Values_f':([5,],[10,]),'Alter_f':([5,20,],[11,25,]),'tipoDatos':([22,],[27,]),'valorDato':([30,33,],[34,40,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> Proced","S'",1,None,None,None),
  ('Proced -> Proc ID LPARENTHESIS instrucciones RPARENTHESIS SEMMICOLOM','Proced',6,'p_Proced','Parser.py',19),
  ('Proced -> Proc PRINCIPAL LPARENTHESIS RPARENTHESIS SEMMICOLOM','Proced',5,'p_Proced','Parser.py',20),
  ('instrucciones -> varDeclaration','instrucciones',1,'p_instrucciones','Parser.py',24),
  ('instrucciones -> Values_f','instrucciones',1,'p_instrucciones','Parser.py',25),
  ('instrucciones -> Alter_f','instrucciones',1,'p_instrucciones','Parser.py',26),
  ('Values_f -> Values LPARENTHESIS ID COMMA valorDato RPARENTHESIS SEMMICOLOM','Values_f',7,'p_Values_f','Parser.py',31),
  ('Values_f -> LPARENTHESIS ID COMMA Alter_f RPARENTHESIS SEMMICOLOM','Values_f',6,'p_Values_f','Parser.py',32),
  ('Alter_f -> LPARENTHESIS ID COMMA RPARENTHESIS','Alter_f',4,'p_Alter_f','Parser.py',35),
  ('varDeclaration -> New ID LPARENTHESIS tipoDatos COMMA valorDato RPARENTHESIS SEMMICOLOM','varDeclaration',8,'p_varDeclaration','Parser.py',43),
  ('tipoDatos -> Bool','tipoDatos',1,'p_tipoDatos','Parser.py',48),
  ('tipoDatos -> Num','tipoDatos',1,'p_tipoDatos','Parser.py',49),
  ('valorDato -> True','valorDato',1,'p_valorDato','Parser.py',55),
  ('valorDato -> False','valorDato',1,'p_valorDato','Parser.py',56),
  ('valorDato -> Number','valorDato',1,'p_valorDato','Parser.py',57),
]
